In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

1.13.1+cpu


In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as python int 
scalar.item( )

7

In [6]:
#vector
vector=torch.Tensor([7,7])
vector

tensor([7., 7.])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#  MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.Tensor([[[1,2,3],[3,6,9],[2,4,6]]])
TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 6.]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1., 2., 3.],
        [3., 6., 9.],
        [2., 4., 6.]])

In [17]:
### Random tensors 

In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7856, 0.2379, 0.9366, 0.0443],
        [0.1354, 0.3322, 0.4927, 0.4992],
        [0.7820, 0.0706, 0.2894, 0.0562]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
random_image_size_tensor = torch.rand(size= (224,224,3))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
one_to_ten= torch.arange(start=0 , end=1000 , step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [25]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
#float 32 tensor
#tensor datatypes are common errors , whatch out !
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

In [29]:
#getting info from tensors 
#tensor.dtype
#tensor.shape
#tensor.device
some_tensor=torch.rand(3,4)
some_tensor


tensor([[0.9980, 0.6610, 0.4813, 0.1456],
        [0.2444, 0.5286, 0.9338, 0.8310],
        [0.7373, 0.6995, 0.0209, 0.1874]])

In [30]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"shape of tensor : {some_tensor.shape}")
print(f"Device of tensor : {some_tensor.device}")

tensor([[0.9980, 0.6610, 0.4813, 0.1456],
        [0.2444, 0.5286, 0.9338, 0.8310],
        [0.7373, 0.6995, 0.0209, 0.1874]])
Datatype of tensor : torch.float32
shape of tensor : torch.Size([3, 4])
Device of tensor : cpu


In [31]:
tensor = torch.tensor([1,2,3])
tensor+10  
tensor

tensor([1, 2, 3])

In [32]:
tensor = tensor* 10
tensor

tensor([10, 20, 30])

In [33]:
tensor - 10

tensor([ 0, 10, 20])

In [34]:
tensor / 10
  

tensor([1., 2., 3.])

In [35]:
tensor = torch.tensor([1,2,3])
print(tensor,"*",tensor)
print(f"Equals : {tensor*tensor}")
print(f"matrix dot product : {torch.matmul(tensor,tensor)}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])
matrix dot product : 14


In [36]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
tensor_B.T

print (F"tensor A shape :\n {tensor_A.shape}")
print (F"tensor B shape :\n {tensor_B.shape}")
print (F"tensor B transport shape :\n {tensor_B.T.shape}")
print (f"the MATRIX multipication :\n {torch.matmul(tensor_A,tensor_B.T)}")





tensor A shape :
 torch.Size([3, 2])
tensor B shape :
 torch.Size([3, 2])
tensor B transport shape :
 torch.Size([2, 3])
the MATRIX multipication :
 tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [37]:
x = torch.arange(0,100,10)
print(x)
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.sum())
print(x.argmin())
print(x.argmax())


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(90)
tensor(45.)
tensor(450)
tensor(0)
tensor(9)


In [38]:
#reshaping, sracking , squeezing and unsqueezing tensors , permute 
import torch
x = torch.arange (1. , 10.)
x , x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [39]:
x_reshaped = x.reshape(1,9)
print (f"{x_reshaped} \n  {x_reshaped.shape}")
x1 = x.reshape(9,1)
x1 , x1.shape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
  torch.Size([1, 9])


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [40]:
z= x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [41]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [42]:
x_stacked = torch.stack([x,x,x,x] , dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [43]:
x_squeezed = x_reshaped.squeeze()
print(f"the main tensor : {x_reshaped} \nthe shape of it : {x_reshaped.shape} \n")
print(f"new tensor : {x_squeezed} \nthe shape of it : {x_reshaped.squeeze().shape}")


the main tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
the shape of it : torch.Size([1, 9]) 

new tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
the shape of it : torch.Size([9])


In [44]:
print(f"previous target : {x_squeezed} \nthe shape of it : {x_squeezed.shape} ")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"the new tensor : {x_unsqueezed} \nthe shape of it : {x_unsqueezed.shape}")

previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
the shape of it : torch.Size([9]) 
the new tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
the shape of it : torch.Size([1, 9])


In [45]:
x_original = torch.rand(size=(224 , 224 , 3))
x_permuted = x_original.permute(2,0,1)
print(f"previous shape : {x_original.shape} \nthe new shape : {x_permuted.shape}")


previous shape : torch.Size([224, 224, 3]) 
the new shape : torch.Size([3, 224, 224])


In [46]:
x_original[0,0,0]

tensor(0.9026)

In [47]:
x_original[0,0,0]=728218
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

In [48]:
#indexing 
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [49]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
x[0][0]

tensor([1, 2, 3])

In [51]:
x[0][2][2]

tensor(9)

In [52]:
x[:,0] 

tensor([[1, 2, 3]])

In [53]:
x[:,:,1]

tensor([[2, 5, 8]])

In [54]:
x[:,1,1]

tensor([5])

In [55]:
x[0,0,:]

tensor([1, 2, 3])

In [56]:
x[:,:,2]

tensor([[3, 6, 9]])

In [57]:
#PyTorch tensors and NumPy
#numpy array to tensor 
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor
#array dtype = float 64
#tensor dtype = float 32
 

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [58]:
torch.arange(1.0 , 8.0).dtype

torch.float32

In [59]:
array.dtype

dtype('float64')

In [60]:
tensor.dtype

torch.float64

In [61]:
#change the array and see wut happens to tensor 
array = array+1
array,tensor
# tensor doesn't change

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [62]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [63]:
#change the tensor , what happens to array ?
tensor = tensor+1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [64]:
# reproducibility(trying to take random out of random) 
import torch
random_tensor_A= torch.rand(3,4)
random_tensor_B= torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)


tensor([[0.2331, 0.0510, 0.2048, 0.8515],
        [0.2199, 0.0732, 0.2806, 0.3942],
        [0.8202, 0.4128, 0.0776, 0.1570]])
tensor([[0.2368, 0.8896, 0.2476, 0.2260],
        [0.5460, 0.7049, 0.0375, 0.6276],
        [0.3429, 0.0494, 0.3194, 0.9504]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [65]:
import torch
RANDOM_SEED= 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [66]:
import torch
torch.cuda.is_available()

False